# -*- coding: utf-8 -*-
"""CNN_CORVIT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bS85Q5TK_lO1iYxFKKRpt4hNzLzY_7ZO
"""

print('Ali Ahmed')

import tensorflow as tf
import tensorflow_datasets as tfds
(ds_train, ds_test), ds_info = tfds.load('malaria',split=['train[:80%]', 'train[80%:]'],  as_supervised=True, with_info=True)

IMG_SIZE = 128
def preprocess(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

train_ds = ds_train.map(preprocess).shuffle(1000).batch(32)
test_ds  = ds_test.map(preprocess).batch(32)

for image, label in train_ds.take(1):
    print(f"Image shape: {image.shape}")
    print(f"Label batch: {label[:10].numpy()}")

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(train_ds, epochs=20, validation_data=test_ds)

test_loss, test_acc = model.evaluate(test_ds)
print(f"\n Test Accuracy: {test_acc * 100:.2f}%")

model.save("cnn_corvit.h5")
print("Model saved successfully as cnn_corvit.h5")

from google.colab import files
files.download('cnn_corvit.h5')

